### ISSUE TITLE
what is the system matrix 

### ISSUE THREAD

**Issue by Jimmy-Bots** [cshen1024/BC_DPM#2]
how can i find it

lmat = scipy.io.loadmat(**'./put system matrix here'**)
if 'S' in lmat.keys():
    S = lmat['S']
else:
    S = lmat['A']
S_coo = S.tocoo()  # COO

**Comment by sunqiqi123** [comment]
Excuse me, have you found lmat = scipy.io.loadmat('./put system matrix here')?

**Comment by Jimmy-312** [comment]
我已收到您的来信，会尽快回复。
